GET http://localhost:8080/v1/weather/actual/Rzeszow
Content-Type: application/json
Accept: application/json
###

GET http://localhost:8080/v1/weather/daily/Rzeszow
Content-Type: application/json
Accept: application/json
###
